#!/usr/bin/env python

import sys
import cmd
from ROOT import TFile, RooFit, RooStats

def main( input_file, workspacename):

    tf = TFile( input_file )

    ws = tf.Get(workspacename)
    
    mc = ws.obj("ModelConfig");
    mc.Print()

if __name__ == "__main__":

    if len(sys.argv) == 3:
        input_file    = sys.argv[1]
        workspacename = sys.argv[2]
        main(input_file, workspacename)
    else:
        print("Usage: printmc <input-file>")
